# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'botoinfomapa.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BotoInfoMapa(object):
    def setupUi(self, BotoInfoMapa):
        BotoInfoMapa.setObjectName("BotoInfoMapa")
        BotoInfoMapa.resize(500, 314)
        BotoInfoMapa.setMinimumSize(QtCore.QSize(500, 0))
        BotoInfoMapa.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("Notram")
        BotoInfoMapa.setFont(font)
        self.horizontalLayout = QtWidgets.QHBoxLayout(BotoInfoMapa)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(BotoInfoMapa)
        self.frame.setMinimumSize(QtCore.QSize(0, 10))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 10))
        self.frame.setStyleSheet("background-color: #666666\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(BotoInfoMapa)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setMinimumSize(QtCore.QSize(10, 0))
        self.frame_5.setMaximumSize(QtCore.QSize(10, 16777215))
        self.frame_5.setStyleSheet("background-color: #666666\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setLineWidth(0)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4.addWidget(self.frame_5)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setMinimumSize(QtCore.QSize(450, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(450, 16777215))
        self.frame_4.setStyleSheet("background-color: #888888")
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setLineWidth(0)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout.setContentsMargins(5, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.lblTitol = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.lblTitol.setFont(font)
        self.lblTitol.setStyleSheet("background-color: #888888;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.lblTitol.setObjectName("lblTitol")
        self.gridLayout.addWidget(self.lblTitol, 0, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.frame_4)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setStyleSheet("background-color: #666666")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setLineWidth(0)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_7 = QtWidgets.QFrame(BotoInfoMapa)
        self.frame_7.setMinimumSize(QtCore.QSize(10, 0))
        self.frame_7.setMaximumSize(QtCore.QSize(10, 16777215))
        self.frame_7.setStyleSheet("background-color: #dddddd\n"
"")
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setLineWidth(0)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_3.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(BotoInfoMapa)
        self.frame_8.setMinimumSize(QtCore.QSize(450, 0))
        self.frame_8.setMaximumSize(QtCore.QSize(450, 16777215))
        self.frame_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setLineWidth(0)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lblImatge = QtWidgets.QLabel(self.frame_8)
        self.lblImatge.setMinimumSize(QtCore.QSize(200, 200))
        self.lblImatge.setMaximumSize(QtCore.QSize(200, 200))
        self.lblImatge.setText("")
        self.lblImatge.setPixmap(QtGui.QPixmap("imatges//gats.png"))
        self.lblImatge.setObjectName("lblImatge")
        self.horizontalLayout_5.addWidget(self.lblImatge)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame_8)
        self.label_3.setMinimumSize(QtCore.QSize(0, 30))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.textEdit = QtWidgets.QTextEdit(self.frame_8)
        self.textEdit.setStyleSheet("")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_2.addWidget(self.textEdit)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(BotoInfoMapa)
        self.frame_9.setStyleSheet("background-color: #dddddd\n"
"")
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setLineWidth(0)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_3.setContentsMargins(3, 0, 3, 0)
        self.verticalLayout_3.setSpacing(1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.b1 = QtWidgets.QPushButton(self.frame_9)
        self.b1.setMinimumSize(QtCore.QSize(30, 30))
        self.b1.setMaximumSize(QtCore.QSize(30, 30))
        self.b1.setObjectName("b1")
        self.verticalLayout_3.addWidget(self.b1)
        self.b2 = QtWidgets.QPushButton(self.frame_9)
        self.b2.setMinimumSize(QtCore.QSize(30, 30))
        self.b2.setMaximumSize(QtCore.QSize(30, 30))
        self.b2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imatges//qgis3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b2.setIcon(icon)
        self.b2.setIconSize(QtCore.QSize(28, 28))
        self.b2.setObjectName("b2")
        self.verticalLayout_3.addWidget(self.b2)
        self.b3 = QtWidgets.QPushButton(self.frame_9)
        self.b3.setMinimumSize(QtCore.QSize(30, 30))
        self.b3.setMaximumSize(QtCore.QSize(30, 30))
        self.b3.setText("")
        self.b3.setObjectName("b3")
        self.verticalLayout_3.addWidget(self.b3)
        self.b4 = QtWidgets.QPushButton(self.frame_9)
        self.b4.setMinimumSize(QtCore.QSize(30, 30))
        self.b4.setMaximumSize(QtCore.QSize(30, 30))
        self.b4.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("imatges//information-outline.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b4.setIcon(icon1)
        self.b4.setIconSize(QtCore.QSize(30, 30))
        self.b4.setObjectName("b4")
        self.verticalLayout_3.addWidget(self.b4)
        self.horizontalLayout_3.addWidget(self.frame_9)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.frame_6 = QtWidgets.QFrame(BotoInfoMapa)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 10))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 20))
        self.frame_6.setStyleSheet("background-color: #dddddd\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setLineWidth(0)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout.addWidget(self.frame_6)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(BotoInfoMapa)
        QtCore.QMetaObject.connectSlotsByName(BotoInfoMapa)

    def retranslateUi(self, BotoInfoMapa):
        _translate = QtCore.QCoreApplication.translate
        BotoInfoMapa.setWindowTitle(_translate("BotoInfoMapa", "Form"))
        self.lblTitol.setText(_translate("BotoInfoMapa", "Planol d\'Informació Urbanística"))
        self.label_3.setText(_translate("BotoInfoMapa", "Lorem Ipsum"))
        self.textEdit.setHtml(_translate("BotoInfoMapa", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Open Sans,Arial,sans-serif\'; font-size:8pt; color:#000000; background-color:#ffffff;\">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</span></p></body></html>"))
        self.b1.setText(_translate("BotoInfoMapa", "Obrir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BotoInfoMapa = QtWidgets.QWidget()
    ui = Ui_BotoInfoMapa()
    ui.setupUi(BotoInfoMapa)
    BotoInfoMapa.show()
    sys.exit(app.exec_())

