# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'finestraDelimitadors.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(497, 228)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(-130, 190, 621, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.cbDelimitador = QtWidgets.QComboBox(Dialog)
        self.cbDelimitador.setGeometry(QtCore.QRect(160, 70, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cbDelimitador.setFont(font)
        self.cbDelimitador.setAccessibleName("")
        self.cbDelimitador.setObjectName("cbDelimitador")
        self.cbDelimitador.addItem("")
        self.cbDelimitador.addItem("")
        self.cbDelimitador.addItem("")
        self.cbDelimitador.addItem("")
        self.cbDelimitador.setItemText(3, "")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 60, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.cbDelX = QtWidgets.QComboBox(Dialog)
        self.cbDelX.setGeometry(QtCore.QRect(420, 70, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cbDelX.setFont(font)
        self.cbDelX.setAccessibleName("")
        self.cbDelX.setObjectName("cbDelX")
        self.cbDelX.addItem("")
        self.cbDelX.addItem("")
        self.cbDelX.addItem("")
        self.cbDelX.addItem("")
        self.cbDelX.setItemText(3, "")
        self.cbDelY = QtWidgets.QComboBox(Dialog)
        self.cbDelY.setGeometry(QtCore.QRect(420, 120, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cbDelY.setFont(font)
        self.cbDelY.setAccessibleName("")
        self.cbDelY.setObjectName("cbDelY")
        self.cbDelY.addItem("")
        self.cbDelY.addItem("")
        self.cbDelY.addItem("")
        self.cbDelY.addItem("")
        self.cbDelY.setItemText(3, "")
        self.cbDelProjeccio = QtWidgets.QComboBox(Dialog)
        self.cbDelProjeccio.setGeometry(QtCore.QRect(160, 120, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cbDelProjeccio.setFont(font)
        self.cbDelProjeccio.setAccessibleName("")
        self.cbDelProjeccio.setObjectName("cbDelProjeccio")
        self.cbDelProjeccio.addItem("")
        self.cbDelProjeccio.addItem("")
        self.cbDelProjeccio.addItem("")
        self.cbDelProjeccio.addItem("")
        self.cbDelProjeccio.setItemText(3, "")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(300, 110, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(300, 60, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.leNomCapa = QtWidgets.QLineEdit(Dialog)
        self.leNomCapa.setGeometry(QtCore.QRect(190, 20, 301, 31))
        self.leNomCapa.setObjectName("leNomCapa")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 0, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.cbDelimitador.setItemText(0, _translate("Dialog", ","))
        self.cbDelimitador.setItemText(1, _translate("Dialog", ";"))
        self.cbDelimitador.setItemText(2, _translate("Dialog", "|"))
        self.label.setText(_translate("Dialog", "Delimitador:"))
        self.cbDelX.setItemText(0, _translate("Dialog", ","))
        self.cbDelX.setItemText(1, _translate("Dialog", ";"))
        self.cbDelX.setItemText(2, _translate("Dialog", "|"))
        self.cbDelY.setItemText(0, _translate("Dialog", ","))
        self.cbDelY.setItemText(1, _translate("Dialog", ";"))
        self.cbDelY.setItemText(2, _translate("Dialog", "|"))
        self.cbDelProjeccio.setItemText(0, _translate("Dialog", ","))
        self.cbDelProjeccio.setItemText(1, _translate("Dialog", ";"))
        self.cbDelProjeccio.setItemText(2, _translate("Dialog", "|"))
        self.label_2.setText(_translate("Dialog", "Projecció:"))
        self.label_3.setText(_translate("Dialog", "Camp Y"))
        self.label_4.setText(_translate("Dialog", "Camp X"))
        self.label_5.setText(_translate("Dialog", "Nom de capa"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

