# --------------------------------------------------------------------------------------------
###
### Búsqueda de un bug abierto por título
###
GET https://api.github.com/search/issues
    ?q=repo:SistemesInformacioTerritorial/QVista+state:open+label:bug+Prueba+bug+in:title
Authorization: token a0d8ae1c0a58b63a95538efd954730e611531680
Accept: application/json
Time-Zone: Europe/Madrid
User-Agent: qVista

###
### Lista de Commits de un fichero (puede añadirse parámetro sha=rama)
###
GET http://api.github.com/repos/SistemesInformacioTerritorial/QVista/commits
    ?path=moduls/QvLlegenda.py
Authorization: token a0d8ae1c0a58b63a95538efd954730e611531680
Accept: application/json
Time-Zone: Europe/Madrid
User-Agent: qVista
