# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\projectes_py\novageo\NG_ConsultarVials.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(472, 520)
        Dialog.setMaximumSize(QtCore.QSize(472, 520))
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(False)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 9, 7, 1, 2)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 9, 9, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 3)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(Dialog)
        self.dateTimeEdit.setCalendarPopup(True)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout.addWidget(self.dateTimeEdit, 4, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 3, 1, 2)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout.addWidget(self.comboBox_2, 2, 3, 1, 2)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 3)
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 1, 3, 1, 2)
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 2, 5, 1, 5)
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 3, 1, 1, 4)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 2)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 5, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(Dialog)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout.addWidget(self.comboBox_3, 5, 2, 1, 1)
        self.tableView = QtWidgets.QTableView(Dialog)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 8, 0, 1, 10)
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 7, 8, 1, 2)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(Dialog)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.gridLayout.addWidget(self.comboBox_4, 6, 1, 1, 3)
        self.checkBox_2 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 7, 2, 1, 3)
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 7, 7, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 9, 3, 1, 2)
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setCheckable(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 9, 0, 1, 3)
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(Dialog)
        self.dateTimeEdit_2.setCalendarPopup(True)
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.gridLayout.addWidget(self.dateTimeEdit_2, 4, 6, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Consulta vials. Selecció"))
        self.pushButton.setText(_translate("Dialog", "Consultar"))
        self.pushButton_2.setText(_translate("Dialog", "Tancar"))
        self.label_2.setText(_translate("Dialog", "Tipus de vial"))
        self.dateTimeEdit.setDisplayFormat(_translate("Dialog", "dd/MM/yyyy"))
        self.label_3.setText(_translate("Dialog", "Nom"))
        self.label.setText(_translate("Dialog", "Codi de vial"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "Comença per..."))
        self.comboBox_2.setItemText(1, _translate("Dialog", "Contenint ..."))
        self.label_4.setText(_translate("Dialog", "Data Aprovació"))
        self.comboBox.setItemText(0, _translate("Dialog", "Era"))
        self.comboBox.setItemText(1, _translate("Dialog", "Apartat"))
        self.comboBox.setItemText(2, _translate("Dialog", "Camí"))
        self.comboBox.setItemText(3, _translate("Dialog", "Carrer"))
        self.checkBox.setText(_translate("Dialog", "Cercar per variants"))
        self.label_5.setText(_translate("Dialog", "Propietat"))
        self.label_7.setText(_translate("Dialog", "fins a"))
        self.comboBox_3.setItemText(0, _translate("Dialog", "Publica"))
        self.comboBox_3.setItemText(1, _translate("Dialog", "Privada"))
        self.pushButton_6.setText(_translate("Dialog", "Tancar"))
        self.label_6.setText(_translate("Dialog", "Nom"))
        self.comboBox_4.setItemText(0, _translate("Dialog", "Nom Oficial"))
        self.comboBox_4.setItemText(1, _translate("Dialog", "Nom Popular"))
        self.comboBox_4.setItemText(2, _translate("Dialog", "Nom no Oficial"))
        self.comboBox_4.setItemText(3, _translate("Dialog", "Nom Gèneric"))
        self.checkBox_2.setText(_translate("Dialog", "Només donats de baixa"))
        self.pushButton_5.setText(_translate("Dialog", "Filtar"))
        self.pushButton_4.setText(_translate("Dialog", "Presentar informe"))
        self.pushButton_3.setText(_translate("Dialog", "Dades historiques"))
        self.dateTimeEdit_2.setDisplayFormat(_translate("Dialog", "dd/MM/yyyy"))

