# -*- coding: utf-8 -*-
"""
/***************************************************************************
 soroll
                                 A QGIS plugin
 soroll
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-08-23
        git sha              : $Format:%H$
        copyright            : (C) 2024 by soroll
        email                : soroll
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction


# from qgis.core import QgsProject, Qgis, QgsProcessingUtils, QgsProcessingContext
from PyQt5.QtWidgets import QApplication
from qgis.PyQt.QtCore import Qt, QVariant
from qgis.core import  QgsMapLayerType, QgsMapLayer


from qgis.core import QgsPointXY, QgsProject, Qgis, QgsFeature, QgsVectorLayer, QgsField, QgsVectorLayerEditUtils, \
                    QgsFeatureRequest, QgsRectangle, QgsDistanceArea, QgsGeometry, \
                    QgsPoint, QgsTextFormat, QgsTextBufferSettings,  QgsPalLayerSettings, \
                    QgsVectorLayerSimpleLabeling, QgsPropertyCollection, QgsProperty, \
                    QgsVectorDataProvider, QgsVectorFileWriter, QgsCoordinateReferenceSystem, \
                    QgsProcessingFeatureSourceDefinition, QgsAction
from PyQt5.QtGui  import QColor,  QFont, QPalette,  QTextCursor, QTextCharFormat

from qgis import processing
# import my_processing_module as mp
from .soroll_processing import *


import sys
import os


# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .soroll_dialog import sorollDialog
import os.path


class soroll:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'soroll_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&soroll')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('soroll', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action




    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/soroll/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'soroll'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True






    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&soroll'),
                action)
            self.iface.removeToolBarIcon(action)

    # Importar el módulo
    




    def barraEscala(self):
        from qgis.core import QgsProject
        
        medidaBarraEscala = self.dlg.medidaBarraEscala.text()


        # Configuración de la barra de escala
        QgsProject.instance().writeEntry("ScaleBar", "/Color", "#ff9e00")
        QgsProject.instance().writeEntry("ScaleBar", "/MarginH", 0)
        QgsProject.instance().writeEntry("ScaleBar", "/MarginV", 0)
        QgsProject.instance().writeEntry("ScaleBar", "/MarginUnit", "MM")
        QgsProject.instance().writeEntry("ScaleBar", "/Style", 0)
        QgsProject.instance().writeEntry("ScaleBar", "/Placement", 1)
        QgsProject.instance().writeEntry("ScaleBar", "/PreferredSize", medidaBarraEscala)
        QgsProject.instance().writeEntry("ScaleBar", "/Enabled", True)

        QgsProject.instance().write()
        filename = QgsProject.instance().fileName()
        self.iface.addProject(filename)

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = sorollDialog()

        self.dlg.barraEscala.clicked.connect(self.barraEscala)  

        soroll_dialog(self.dlg)
