# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\μqVista.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(935, 600)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 144, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(182, 216, 233))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(151, 180, 194))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 72, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(80, 96, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 144, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(188, 199, 205))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 144, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(182, 216, 233))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(151, 180, 194))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 72, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(80, 96, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 144, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(188, 199, 205))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 72, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 144, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(182, 216, 233))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(151, 180, 194))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 72, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(80, 96, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 72, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 72, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 144, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 144, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 144, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.frame_2.setPalette(palette)
        self.frame_2.setAutoFillBackground(True)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblTitol = QtWidgets.QLabel(self.frame_2)
        self.lblTitol.setText("")
        self.lblTitol.setObjectName("lblTitol")
        self.horizontalLayout.addWidget(self.lblTitol)
        self.bVeureLlegenda = QtWidgets.QPushButton(self.frame_2)
        self.bVeureLlegenda.setMinimumSize(QtCore.QSize(24, 24))
        self.bVeureLlegenda.setMaximumSize(QtCore.QSize(24, 24))
        self.bVeureLlegenda.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Imatges/map-legend.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bVeureLlegenda.setIcon(icon)
        self.bVeureLlegenda.setObjectName("bVeureLlegenda")
        self.horizontalLayout.addWidget(self.bVeureLlegenda)
        self.bMapeta = QtWidgets.QPushButton(self.frame_2)
        self.bMapeta.setMinimumSize(QtCore.QSize(24, 24))
        self.bMapeta.setMaximumSize(QtCore.QSize(24, 24))
        self.bMapeta.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../Imatges/Mapeta.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bMapeta.setIcon(icon1)
        self.bMapeta.setObjectName("bMapeta")
        self.horizontalLayout.addWidget(self.bMapeta)
        self.bObrirQgis = QtWidgets.QPushButton(self.frame_2)
        self.bObrirQgis.setMinimumSize(QtCore.QSize(24, 24))
        self.bObrirQgis.setMaximumSize(QtCore.QSize(24, 24))
        self.bObrirQgis.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../Imatges/qgis-3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bObrirQgis.setIcon(icon2)
        self.bObrirQgis.setObjectName("bObrirQgis")
        self.horizontalLayout.addWidget(self.bObrirQgis)
        self.bReload = QtWidgets.QPushButton(self.frame_2)
        self.bReload.setMinimumSize(QtCore.QSize(24, 24))
        self.bReload.setMaximumSize(QtCore.QSize(24, 24))
        self.bReload.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../Imatges/reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bReload.setIcon(icon3)
        self.bReload.setObjectName("bReload")
        self.horizontalLayout.addWidget(self.bReload)
        self.bDesar = QtWidgets.QPushButton(self.frame_2)
        self.bDesar.setMinimumSize(QtCore.QSize(24, 24))
        self.bDesar.setMaximumSize(QtCore.QSize(24, 24))
        self.bDesar.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../Imatges/content-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bDesar.setIcon(icon4)
        self.bDesar.setObjectName("bDesar")
        self.horizontalLayout.addWidget(self.bDesar)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frameCentral = QtWidgets.QFrame(self.frame_3)
        self.frameCentral.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameCentral.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameCentral.setObjectName("frameCentral")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frameCentral)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.layCentral = QtWidgets.QHBoxLayout()
        self.layCentral.setObjectName("layCentral")
        self.horizontalLayout_5.addLayout(self.layCentral)
        self.horizontalLayout_3.addWidget(self.frameCentral)
        self.frameBotonera = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameBotonera.sizePolicy().hasHeightForWidth())
        self.frameBotonera.setSizePolicy(sizePolicy)
        self.frameBotonera.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameBotonera.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBotonera.setObjectName("frameBotonera")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frameBotonera)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(7)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.layBotonera = QtWidgets.QVBoxLayout()
        self.layBotonera.setContentsMargins(7, 7, 7, 7)
        self.layBotonera.setObjectName("layBotonera")
        self.bCercarAdreca = QtWidgets.QPushButton(self.frameBotonera)
        self.bCercarAdreca.setMinimumSize(QtCore.QSize(25, 25))
        self.bCercarAdreca.setMaximumSize(QtCore.QSize(25, 25))
        self.bCercarAdreca.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../Imatges/map-search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bCercarAdreca.setIcon(icon5)
        self.bCercarAdreca.setObjectName("bCercarAdreca")
        self.layBotonera.addWidget(self.bCercarAdreca)
        self.bCaptura = QtWidgets.QPushButton(self.frameBotonera)
        self.bCaptura.setMinimumSize(QtCore.QSize(25, 25))
        self.bCaptura.setMaximumSize(QtCore.QSize(25, 25))
        self.bCaptura.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../../Imatges/camera.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bCaptura.setIcon(icon6)
        self.bCaptura.setObjectName("bCaptura")
        self.layBotonera.addWidget(self.bCaptura)
        self.bImprimir = QtWidgets.QPushButton(self.frameBotonera)
        self.bImprimir.setMinimumSize(QtCore.QSize(25, 25))
        self.bImprimir.setMaximumSize(QtCore.QSize(25, 25))
        self.bImprimir.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../../Imatges/printer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bImprimir.setIcon(icon7)
        self.bImprimir.setObjectName("bImprimir")
        self.layBotonera.addWidget(self.bImprimir)
        self.bRetalls = QtWidgets.QPushButton(self.frameBotonera)
        self.bRetalls.setMinimumSize(QtCore.QSize(25, 25))
        self.bRetalls.setMaximumSize(QtCore.QSize(25, 25))
        self.bRetalls.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../../Imatges/tisores.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bRetalls.setIcon(icon8)
        self.bRetalls.setObjectName("bRetalls")
        self.layBotonera.addWidget(self.bRetalls)
        self.bSeleccio = QtWidgets.QPushButton(self.frameBotonera)
        self.bSeleccio.setMinimumSize(QtCore.QSize(25, 25))
        self.bSeleccio.setMaximumSize(QtCore.QSize(25, 25))
        self.bSeleccio.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../../Imatges/select.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bSeleccio.setIcon(icon9)
        self.bSeleccio.setObjectName("bSeleccio")
        self.layBotonera.addWidget(self.bSeleccio)
        self.bMesurar = QtWidgets.QPushButton(self.frameBotonera)
        self.bMesurar.setMinimumSize(QtCore.QSize(25, 25))
        self.bMesurar.setMaximumSize(QtCore.QSize(25, 25))
        self.bMesurar.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../../Imatges/regle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bMesurar.setIcon(icon10)
        self.bMesurar.setObjectName("bMesurar")
        self.layBotonera.addWidget(self.bMesurar)
        self.bNouCanvas = QtWidgets.QPushButton(self.frameBotonera)
        self.bNouCanvas.setMinimumSize(QtCore.QSize(25, 25))
        self.bNouCanvas.setMaximumSize(QtCore.QSize(25, 25))
        self.bNouCanvas.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("../../Imatges/map-plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bNouCanvas.setIcon(icon11)
        self.bNouCanvas.setObjectName("bNouCanvas")
        self.layBotonera.addWidget(self.bNouCanvas)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layBotonera.addItem(spacerItem)
        self.bNoticies = QtWidgets.QPushButton(self.frameBotonera)
        self.bNoticies.setMinimumSize(QtCore.QSize(25, 25))
        self.bNoticies.setMaximumSize(QtCore.QSize(25, 25))
        self.bNoticies.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("../../Imatges/News.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bNoticies.setIcon(icon12)
        self.bNoticies.setObjectName("bNoticies")
        self.layBotonera.addWidget(self.bNoticies)
        self.bAjuda = QtWidgets.QPushButton(self.frameBotonera)
        self.bAjuda.setMinimumSize(QtCore.QSize(25, 25))
        self.bAjuda.setMaximumSize(QtCore.QSize(25, 25))
        self.bAjuda.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("../../Imatges/help-circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bAjuda.setIcon(icon13)
        self.bAjuda.setObjectName("bAjuda")
        self.layBotonera.addWidget(self.bAjuda)
        self.bBugs = QtWidgets.QPushButton(self.frameBotonera)
        self.bBugs.setMinimumSize(QtCore.QSize(25, 25))
        self.bBugs.setMaximumSize(QtCore.QSize(25, 25))
        self.bBugs.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("../../Imatges/bug.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bBugs.setIcon(icon14)
        self.bBugs.setObjectName("bBugs")
        self.layBotonera.addWidget(self.bBugs)
        self.horizontalLayout_4.addLayout(self.layBotonera)
        self.horizontalLayout_3.addWidget(self.frameBotonera)
        self.verticalLayout.addWidget(self.frame_3)
        self.horizontalLayout_2.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 935, 26))
        self.menubar.setObjectName("menubar")
        self.menuMapes = QtWidgets.QMenu(self.menubar)
        self.menuMapes.setObjectName("menuMapes")
        self.menuCapes = QtWidgets.QMenu(self.menubar)
        self.menuCapes.setObjectName("menuCapes")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCat_leg = QtWidgets.QAction(MainWindow)
        self.actionCat_leg.setObjectName("actionCat_leg")
        self.actionNou = QtWidgets.QAction(MainWindow)
        self.actionNou.setObjectName("actionNou")
        self.actionObrir = QtWidgets.QAction(MainWindow)
        self.actionObrir.setObjectName("actionObrir")
        self.actionDesar = QtWidgets.QAction(MainWindow)
        self.actionDesar.setObjectName("actionDesar")
        self.actionAnomena_i_desa = QtWidgets.QAction(MainWindow)
        self.actionAnomena_i_desa.setObjectName("actionAnomena_i_desa")
        self.menuMapes.addAction(self.actionCat_leg)
        self.menuMapes.addSeparator()
        self.menuMapes.addAction(self.actionNou)
        self.menuMapes.addAction(self.actionObrir)
        self.menuMapes.addAction(self.actionDesar)
        self.menuMapes.addAction(self.actionAnomena_i_desa)
        self.menubar.addAction(self.menuMapes.menuAction())
        self.menubar.addAction(self.menuCapes.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuMapes.setTitle(_translate("MainWindow", "Mapes"))
        self.menuCapes.setTitle(_translate("MainWindow", "Capes"))
        self.actionCat_leg.setText(_translate("MainWindow", "Catàleg"))
        self.actionNou.setText(_translate("MainWindow", "Nou"))
        self.actionObrir.setText(_translate("MainWindow", "Obrir"))
        self.actionDesar.setText(_translate("MainWindow", "Desar"))
        self.actionAnomena_i_desa.setText(_translate("MainWindow", "Anomena i desa"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

